spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver


mybatis:
  configuration:
    # 启动结果集自动映射，partial表示部分自动映射
    #    auto-mapping-behavior: partial
    # 开启驼峰命名映射
    mapUnderscoreToCamelCase: true
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml #扫描xml文件
